version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=items_db
      - DB_PASSWORD=root
      - DB_PORT=5432
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=items_db
    ports:
      - "5432:5432"